### ISSUE TITLE
Please make a version for PowerPC Mac

### ISSUE THREAD

**Issue by barracuda156** [jeroen/build-v8-static#1]
Installing from within R does not work even when environment is set to use static libv8.

**Comment by jeroen** [comment]
You posted this exact same issue in the other repository 5 minutes ago: https://github.com/jeroen/V8/issues/132.
You know very well that PPC for Mac is no longer supported by apple or google. Why don't you try to build it yourself?

**Comment by barracuda156** [comment]
I am sorry, I was unsure about where it is more appropriate.

Is there a source code for a static version? Tarball that gets
downloaded is few kilobytes and contains only platform-targeted
scripts.

**Comment by jeroen** [comment]
Your best bet is probably following these steps: https://github.com/homebrew/homebrew-core/blob/master/Formula/v8@3.15.rb

**Comment by barracuda156** [comment]
Thank you, I will try that.
